spring:
  application:
    name: yajalones-app
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  threads:
    virtual:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration   # ✅ adopta BD ya existente
    baseline-on-migrate: true
    clean-disabled: true
  mvc:
    problemdetails:
      enabled: true
  profiles:
    default: dev
server:
  port: 8081
jwt:
  secret: ${SECRET_KEY}
