spring:
  application:
    name: yajalones-app
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  threads:
    virtual:
      enabled: true
  profiles:
    default: dev

server:
  port: 8081




