spring:
  application:
    name: yajalones-app
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  threads:
    virtual:
      enabled: true

  profiles:
    default: dev



